- name: Backup Cisco IOS switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Garantir pasta de backup existe
      file:
        path: /home/semaphore/backup
        state: directory
        mode: '0775'
      delegate_to: localhost

    - name: Executar write memory
      ios_command:
        commands:
          - write memory
      register: wr_output

    - name: Executar show interfaces status
      ios_command:
        commands:
          - show interfaces status
      register: sh_int_status

    - name: Salvar output de show interfaces status em arquivo
      copy:
        content: "{{ sh_int_status.stdout[0] }}"
        dest: "/home/semaphore/backup/{{ inventory_hostname }}-interfaces.txt"
      delegate_to: localhost
