- name: Backup Cisco IOS switches
  hosts: switches
  gather_facts: no

  tasks:
    - name: Salvar configuração no switch (wr)
      ios_command:
        commands:
          - write memory
      become: yes

    - name: Coletar status das interfaces
      ios_command:
        commands:
          - show interface status
        timeout: 120
      register: interface_status

    - name: Salvar saída do show interface status
      copy:
        content: "{{ interface_status.stdout[0] }}"
        dest: "/srv/semaphore-backups/{{ inventory_hostname }}-interfaces.txt"
        owner: saoevcar
        group: users
        mode: '0660'
      become: yes
