---
- name: Teste de conexão SSH com switches
  hosts: all
  gather_facts: no

  tasks:
    - name: Testar conectividade com ping
      ansible.builtin.ping:

    - name: Mostrar config carregada
      debug:
        var: ansible_config_file

    - name: Exibir saída do show version
      debug:
        var: version_output.stdout_lines

    - name: Mostrar config carregada
      debug:
        var: ansible_config_file
