---
- name: Teste de conexão SSH com switches
  hosts: switches
  gather_facts: no

  tasks:
    - name: Testar conectividade com ping
      ansible.builtin.ping:

    - name: Executar show version
      ios_command:
        commands:
          - show version
      register: version_output
      ignore_errors: yes   # evita que o playbook quebre se a conexão falhar

    - name: Exibir saída do show version
      debug:
        var: version_output.stdout_lines

    - name: Mostrar config carregada
      debug:
        var: ansible_config_file
