- name: Coletar informações do switch
  hosts: SAOTS016
  gather_facts: no
  tasks:
    - name: Show running-config
      raw: show running-config
    - name: Show Interfaces status
      raw: show interface status
