- hosts: local
  tasks:
    - name: Teste de ping local
      ping:

    - name: Mostrar mensagem local
      debug:
        msg: "Semaphore está funcionando com Ansible no localhost!"

- hosts: switches
  gather_facts: no
  tasks:
    - name: Coletar informações IOS
      ios_facts:

    - name: Mostrar versão
      debug:
        msg: "Versão: {{ ansible_net_version }}"

    - name: Mostrar hostname
      debug:
        msg: "Hostname: {{ ansible_net_hostname }}"
