- hosts: local
  tasks:
    - name: Teste de ping local
      ping:

    - name: Mostrar mensagem local
      debug:
        msg: "Semaphore está funcionando com Ansible no localhost!"

- hosts: switches
  gather_facts: no
  tasks:
    - name: Mostrar versão IOS
      raw: show version

