- hosts: local
  tasks:
    - name: Teste de ping local
      ping:

    - name: Mostrar mensagem local
      debug:
        msg: "Semaphore está funcionando com Ansible no localhost!"

- hosts: ios_switches
  gather_facts: no
  tasks:
    - name: Executar "show version"
      ios_command:
        commands:
          - show version
      register: versao

    - name: Mostrar saída
      debug:
        var: versao.stdout_lines


